<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-13 05:23
=======
# Generated by Django 5.1.5 on 2025-04-13 06:26
>>>>>>> 6dde96900f5f60f75a1186e9943aeaafae39c3c8

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_text', models.TextField()),
                ('response_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
