# Generated by Django 5.2 on 2025-04-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('json_content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
