# Generated by Django 5.1.5 on 2025-04-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_lead_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='audio_link',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='transcript',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
